[project]
name = "."
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/runner/OpenScholar/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.papersubmission]
path = "contracts/papersubmission.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
